version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs:
  build:
    docker:
      - image: romansainthilaire/oc_lettings_site:latest
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest
  deploy:
    docker:
      - image: romansainthilaire/oc_lettings_site:latest
    steps:
      - checkout
      - run:
          name: Install cURL
          command: |
            sudo apt-get update
            sudo apt-get install -y curl
      - run:
          name: Install Docker
          command: |
            curl https://get.docker.com | bash
      - run: |
          echo "$HEROKU_API_KEY" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
          docker tag romansainthilaire/oc_lettings_site:latest registry.heroku.com/oclettingssite/web
          docker push registry.heroku.com/oclettingssite/web
          heroku container:release web --app=oclettingssite
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
