version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
  python: circleci/python@1.3.3

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest

  heroku_deploy:
    jobs:
      - heroku/deploy-via-git

workflows:
  test_and_deploy:
    jobs:
      - build
      - heroku_deploy:
          requires:
            - build
