version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10
  python: circleci/python@1.3.3

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - heroku/deploy-via-git:
          app-name: oclettingssite
          branch: master
      - run:
          name: Install Heroku CLI
          command: |
            curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - run:
          name: Create superuser
          command: |
            heroku run python manage.py shell << END
            from django.contrib.auth.models import User
            if not User.objects.filter(username='${SUPERUSER_USERNAME}').exists():
                User.objects.create_superuser('${SUPERUSER_USERNAME}', '${SUPERUSER_EMAIL}', '${SUPERUSER_PASSWORD}')
            END
            --app oclettingssite

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
