version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10
  docker: circleci/docker@1.0.1

jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install all dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Check code with Flake8
          command: |
            flake8
      - run:
          name: Run tests with Pytest
          command: |
            pytest

  build_and_push_docker:
    docker:
      - image: docker:20.10.11-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t romansainthilaire/oc_lettings_site:$(git rev-parse --short HEAD) .
      - run:
          name: Login to DockerHub
          command: |
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker image to DockerHub
          command: |
            docker push romansainthilaire/oc_lettings_site:$(git rev-parse --short HEAD)

  deploy_to_heroku:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - heroku/deploy-via-git:
          app-name: $HEROKU_APP_NAME
          branch: master
      - run:
          name: Install Heroku CLI
          command: |
            curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - run:
          name: Create superuser
          command: |
            heroku run python manage.py csu $SUPERUSER_USERNAME $SUPERUSER_PASSWORD --app $HEROKU_APP_NAME

workflows:
  build_and_deploy:
    jobs:
      - build_and_test
      - build_and_push_docker:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - master
      - deploy_to_heroku:
          requires:
            - build_and_push_docker
          filters:
            branches:
              only:
                - master