version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
jobs:
  build:
    docker:
      - image: docker:20.10.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t oclettingssite .
      - save_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          paths:
            - /root/.cache/pip
      - heroku/deploy-via-docker:
          app-name: oclettingssite
          docker-image: oclettingssite
          dockerfile: Dockerfile
          requires-api-key: true
  deploy:
    requires:
      - build
    heroku/deploy-via-git:
      app-name: oclettingssite
