version: 2.1

orbs:
  heroku: circleci/heroku@1.0.2

jobs:
  build-and-deploy:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-compose
      - run:
          name: Build and push Docker image to Heroku
          command: |
            docker-compose -f docker-compose.heroku.yml build web
            docker tag oclettingssite_web registry.heroku.com/oclettingssite/web
            docker push registry.heroku.com/oclettingssite/web
      - heroku/deploy-via-container:
          app-name: oclettingssite
          include-previous-release: true
          release-phase: true
workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy
