version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10
  python: circleci/python@1.3.3

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - heroku/deploy-via-git:
          app-name: oclettingssite
          branch: master
      - run:
          name: Create superuser
          command: |
            heroku run python manage.py shell --app oclettingssite << END
            from django.contrib.auth import get_user_model
            User = get_user_model()
            if not User.objects.filter(username=os.getenv('SUPERUSER_USERNAME')).exists():
                User.objects.create_superuser(os.getenv('SUPERUSER_USERNAME'), os.getenv('SUPERUSER_EMAIL'), os.getenv('SUPERUSER_PASSWORD'))
            END

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
