jobs:
  setup_remote_docker:
    docker:
      - image: circleci/buildpack-deps:stable
    steps:
      - checkout
      - setup_remote_docker
  build:
    docker:
      - image: romansainthilaire/oc_lettings_site:latest
    steps:
      - checkout
      - run:
          name: Install git
          command: apt-get update && apt-get install -y git
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            pytest

  deploy:
    docker:
      - image: romansainthilaire/oc_lettings_site:latest
    steps:
      - checkout
      - run:
          name: Install git
          command: apt-get update && apt-get install -y git
      - heroku/deploy-via-git:
          app-name: $HEROKU_APP_NAME
          branch: master
      - run:
          name: Install Heroku CLI
          command: |
            curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - run:
          name: Create superuser
          command: |
            heroku run python manage.py csu $SUPERUSER_USERNAME $SUPERUSER_PASSWORD --app $HEROKU_APP_NAME

workflows:
  build_and_deploy:
    jobs:
      - setup_remote_docker
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master