version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
  python: circleci/python@1.3.1
jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
workflows:
  build_and_deploy:
    jobs:
      - test:
          name: Run tests
      - deploy:
          name: Deploy to Heroku
          requires:
            - test
