version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10
  python: circleci/python@1.3.3

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - heroku/deploy-via-git:
          app-name: $HEROKU_APP_NAME
          branch: master
      - run:
          name: Install Heroku CLI
          command: |
            curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      - run:
          name: Create admin
          command: |
            heroku run python manage.py createadmin $ADMIN_USERNAME $ADMIN_EMAIL $ADMIN_PASSWORD --app $HEROKU_APP_NAME

workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
